"use strict";
// ─── Core Interfaces ───────────────────────────────────────────────
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getDefaultCustomization = exports.CURATED_TEMPLATES = exports.PREMIUM_LAYOUTS = exports.ThemeRegistry = exports.getGoogleFontsUrl = exports.THEME_PRESETS = exports.ALL_SECTIONS = exports.FONT_OPTIONS = exports.DEFAULT_SECTIONS = void 0;
exports.DEFAULT_SECTIONS = [
    { id: "hero", type: "hero", label: "Hero", visible: true },
    { id: "about", type: "about", label: "About", visible: true },
    { id: "skills", type: "skills", label: "Skills", visible: true },
    { id: "experience", type: "experience", label: "Experience", visible: true },
    { id: "projects", type: "projects", label: "Projects", visible: true },
    { id: "contact", type: "contact", label: "Contact", visible: true },
];
// ─── Font Options ──────────────────────────────────────────────────
exports.FONT_OPTIONS = [
    { label: "Inter", value: "'Inter', sans-serif" },
    { label: "Playfair Display", value: "'Playfair Display', serif" },
    { label: "Lora", value: "'Lora', serif" },
    { label: "Cinzel", value: "'Cinzel', serif" },
    { label: "Manrope", value: "'Manrope', sans-serif" },
    { label: "Poppins", value: "'Poppins', sans-serif" },
    { label: "Space Grotesk", value: "'Space Grotesk', sans-serif" },
    { label: "Outfit", value: "'Outfit', sans-serif" },
    { label: "DM Sans", value: "'DM Sans', sans-serif" },
    { label: "Sora", value: "'Sora', sans-serif" },
    { label: "Syne", value: "'Syne', sans-serif" },
    { label: "Archivo", value: "'Archivo', sans-serif" },
    { label: "Cormorant Garamond", value: "'Cormorant Garamond', serif" },
    { label: "Bebas Neue", value: "'Bebas Neue', sans-serif" },
    { label: "Fira Code", value: "'Fira Code', monospace" },
    { label: "JetBrains Mono", value: "'JetBrains Mono', monospace" },
    { label: "Orbitron", value: "'Orbitron', sans-serif" },
];
exports.ALL_SECTIONS = [
    { id: "hero", type: "hero", label: "Hero", visible: true },
    { id: "about", type: "about", label: "About", visible: true },
    { id: "skills", type: "skills", label: "Skills", visible: true },
    { id: "experience", type: "experience", label: "Experience", visible: true },
    { id: "education", type: "education", label: "Education", visible: true },
    { id: "projects", type: "projects", label: "Projects", visible: true },
    { id: "certifications", type: "certifications", label: "Certifications", visible: true },
    { id: "contact", type: "contact", label: "Contact", visible: true },
];
var defaultSections = exports.ALL_SECTIONS.map(function (s) { return (__assign({}, s)); });
// ─── 22 Template Definitions ───────────────────────────────────────
exports.THEME_PRESETS = [
    {
        id: "executive-obsidian",
        name: "Executive Obsidian",
        description: "Deep black with subtle gold accents and elegant serif typography.",
        preview: "executive-obsidian.png",
        tags: ["professional", "luxury", "dark"],
        recommendedFor: ["executive", "professional"],
        defaultColors: {
            primary: "#1A1A1A",
            secondary: "#2A2A2A",
            accent: "#D4AF37",
            background: "#0A0A0A",
            surface: "#111111",
            text: "#F5F5F5",
            textSecondary: "#A0A0A0"
        },
        defaultFonts: {
            heading: "'Playfair Display', serif",
            headingWeight: "700",
            body: "'Inter', sans-serif",
            bodyWeight: "400",
            mono: "'JetBrains Mono', monospace"
        },
        animationProfile: {
            scrollType: "fade-up",
            scrollThreshold: 0.1,
            hoverEffects: ["lift"],
            staggerReveal: true,
            staggerDelay: 100,
            staggerIncrement: 50,
            reducedMotion: false
        },
        visualStyle: {
            glassmorphism: true,
            glassBlur: 12,
            glassOpacity: 0.05,
            shadowLevel: "lg",
            auroraBackground: false,
            auroraColors: [],
            meshGradient: false,
            meshColors: [],
            spotlightEffect: true,
            spotlightColor: "rgba(212, 175, 55, 0.1)",
            patternOverlay: "none",
            gradientAngle: 145
        },
        supportsImage: true,
        sections: exports.DEFAULT_SECTIONS
    },
    {
        id: "midnight-cobalt",
        name: "Midnight Cobalt",
        description: "Deep blue gradient with bright cyan accents for modern tech executives.",
        preview: "midnight-cobalt.png",
        tags: ["tech", "modern", "blue"],
        recommendedFor: ["executive", "developer"],
        defaultColors: {
            primary: "#0B3D91",
            secondary: "#1E5FBC",
            accent: "#00E5FF",
            background: "#020B1A",
            surface: "#051329",
            text: "#FFFFFF",
            textSecondary: "#8AB4F8"
        },
        defaultFonts: {
            heading: "'Outfit', sans-serif",
            headingWeight: "800",
            body: "'Inter', sans-serif",
            bodyWeight: "400",
            mono: "'Fira Code', monospace"
        },
        animationProfile: {
            scrollType: "scale-up",
            scrollThreshold: 0.15,
            hoverEffects: ["glow", "lift"],
            staggerReveal: true,
            staggerDelay: 100,
            staggerIncrement: 50,
            reducedMotion: false
        },
        visualStyle: {
            glassmorphism: true,
            glassBlur: 16,
            glassOpacity: 0.1,
            shadowLevel: "glow",
            auroraBackground: true,
            auroraColors: ["#00E5FF10", "#0B3D9110"],
            meshGradient: true,
            meshColors: ["#020B1A", "#0B3D91"],
            spotlightEffect: true,
            spotlightColor: "rgba(0, 229, 255, 0.15)",
            patternOverlay: "grid",
            gradientAngle: 180
        },
        supportsImage: true,
        sections: exports.DEFAULT_SECTIONS
    },
    {
        id: "ivory-minimalist",
        name: "Ivory Minimalist",
        description: "Warm off-white background with stark black text and clean architectural lines.",
        preview: "ivory-minimalist.png",
        tags: ["clean", "minimal", "light"],
        recommendedFor: ["designer", "professional"],
        defaultColors: {
            primary: "#F8F9FA",
            secondary: "#E9ECEF",
            accent: "#000000",
            background: "#FFFFFF",
            surface: "#F8F9FA",
            text: "#111827",
            textSecondary: "#6B7280"
        },
        defaultFonts: {
            heading: "'Inter', sans-serif",
            headingWeight: "600",
            body: "'Inter', sans-serif",
            bodyWeight: "400",
            mono: "'Roboto Mono', monospace"
        },
        animationProfile: {
            scrollType: "fade-in",
            scrollThreshold: 0.1,
            hoverEffects: ["lift"],
            staggerReveal: false,
            staggerDelay: 0,
            staggerIncrement: 0,
            reducedMotion: true
        },
        visualStyle: {
            glassmorphism: false,
            glassBlur: 0,
            glassOpacity: 1,
            shadowLevel: "sm",
            auroraBackground: false,
            auroraColors: [],
            meshGradient: false,
            meshColors: [],
            spotlightEffect: false,
            spotlightColor: "",
            patternOverlay: "none",
            gradientAngle: 180
        },
        supportsImage: true,
        sections: exports.DEFAULT_SECTIONS
    },
    {
        id: "slate-rust",
        name: "Slate & Rust",
        description: "Slate grey background with muted rust accents and modern geometric typography.",
        preview: "slate-rust.png",
        tags: ["modern", "corporate", "warm"],
        recommendedFor: ["professional", "freelancer"],
        defaultColors: {
            primary: "#2F3E46",
            secondary: "#354F52",
            accent: "#E07A5F",
            background: "#1E2426",
            surface: "#283337",
            text: "#F4F1DE",
            textSecondary: "#9CA3AF"
        },
        defaultFonts: {
            heading: "'Space Grotesk', sans-serif",
            headingWeight: "700",
            body: "'Roboto', sans-serif",
            bodyWeight: "400",
            mono: "'Space Mono', monospace"
        },
        animationProfile: {
            scrollType: "slide-left",
            scrollThreshold: 0.15,
            hoverEffects: ["scale"],
            staggerReveal: true,
            staggerDelay: 150,
            staggerIncrement: 75,
            reducedMotion: false
        },
        visualStyle: {
            glassmorphism: true,
            glassBlur: 8,
            glassOpacity: 0.2,
            shadowLevel: "md",
            auroraBackground: false,
            auroraColors: [],
            meshGradient: false,
            meshColors: [],
            spotlightEffect: false,
            spotlightColor: "",
            patternOverlay: "dots",
            gradientAngle: 135
        },
        supportsImage: true,
        sections: exports.DEFAULT_SECTIONS
    },
    {
        id: "neon-cyber",
        name: "Neon Cyber",
        description: "Extremely dark purple with neon pink and cyan gradients for creative edge.",
        preview: "neon-cyber.png",
        tags: ["creative", "neon", "dark"],
        recommendedFor: ["developer", "designer"],
        defaultColors: {
            primary: "#120428",
            secondary: "#2A0845",
            accent: "#FF007F",
            background: "#080112",
            surface: "#180633",
            text: "#FFFFFF",
            textSecondary: "#00E5FF"
        },
        defaultFonts: {
            heading: "'Outfit', sans-serif",
            headingWeight: "900",
            body: "'Inter', sans-serif",
            bodyWeight: "400",
            mono: "'Fira Code', monospace"
        },
        animationProfile: {
            scrollType: "flip",
            scrollThreshold: 0.2,
            hoverEffects: ["glow", "border-glow"],
            staggerReveal: true,
            staggerDelay: 200,
            staggerIncrement: 100,
            reducedMotion: false
        },
        visualStyle: {
            glassmorphism: true,
            glassBlur: 24,
            glassOpacity: 0.15,
            shadowLevel: "glow",
            auroraBackground: true,
            auroraColors: ["#FF007F20", "#00E5FF20"],
            meshGradient: true,
            meshColors: ["#080112", "#2A0845"],
            spotlightEffect: true,
            spotlightColor: "rgba(255, 0, 127, 0.2)",
            patternOverlay: "waves",
            gradientAngle: 215
        },
        supportsImage: true,
        sections: exports.DEFAULT_SECTIONS
    },
    // ── Student Templates (5) ──
    {
        id: "student-scholar",
        name: "Scholar",
        description: "Academic-focused layout with classic serif typography and refined spacing.",
        preview: "",
        tags: ["Academic", "Minimal", "Clean"],
        recommendedFor: ["student"],
        defaultColors: { primary: "#2563EB", secondary: "#F8FAFC", accent: "#1E40AF", background: "#FFFFFF", surface: "#F1F5F9", text: "#1E293B", textSecondary: "#64748B" },
        defaultFonts: { heading: "'Playfair Display', serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 80, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "sm", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "student-spark",
        name: "Spark",
        description: "Vibrant and energetic design with playful dot patterns and bold accents.",
        preview: "",
        tags: ["Vibrant", "Creative", "Student"],
        recommendedFor: ["student"],
        defaultColors: { primary: "#8B5CF6", secondary: "#F5F3FF", accent: "#D946EF", background: "#FAFAFA", surface: "#FFFFFF", text: "#1E1B4B", textSecondary: "#6366F1" },
        defaultFonts: { heading: "'Outfit', sans-serif", headingWeight: "800", body: "'DM Sans', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "scale-up", scrollThreshold: 0.1, hoverEffects: ["scale"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 12, glassOpacity: 0.08, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "dots", gradientAngle: 135 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "student-editorial",
        name: "Editorial",
        description: "High-end magazine style with premium serif typography and expansive whitespace.",
        preview: "",
        tags: ["Editorial", "Luxury", "Minimal"],
        recommendedFor: ["student", "professional"],
        defaultColors: { primary: "#1A1A1A", secondary: "#F4F4F0", accent: "#C19A6B", background: "#FDFDFD", surface: "#F4F4F0", text: "#1A1A1A", textSecondary: "#666666" },
        defaultFonts: { heading: "'Playfair Display', serif", headingWeight: "600", body: "'Manrope', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-in", scrollThreshold: 0.2, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 150, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "none", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "student-brutalist",
        name: "Brutalist",
        description: "Large, high-contrast typography with a raw, modern aesthetic.",
        preview: "",
        tags: ["Brutalist", "Bold", "Modern"],
        recommendedFor: ["student", "freelancer"],
        defaultColors: { primary: "#000000", secondary: "#FACC15", accent: "#000000", background: "#FFFFFF", surface: "#FFFFFF", text: "#000000", textSecondary: "#000000" },
        defaultFonts: { heading: "'Space Grotesk', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "500", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "slide-right", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 50, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "none", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "student-nexus",
        name: "Nexus",
        description: "Tech-forward layout with sleek glass cards and soft gradient highlights.",
        preview: "",
        tags: ["Modern", "Tech", "Sleek"],
        recommendedFor: ["student", "developer"],
        defaultColors: { primary: "#6366F1", secondary: "#EEF2FF", accent: "#4F46E5", background: "#FFFFFF", surface: "#F8FAFC", text: "#1E293B", textSecondary: "#475569" },
        defaultFonts: { heading: "'Outfit', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "blur-in", scrollThreshold: 0.15, hoverEffects: ["lift", "glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: true, glassBlur: 8, glassOpacity: 0.05, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: true, spotlightColor: "#6366F110", patternOverlay: "none", gradientAngle: 135 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    // ── Fresher Templates (4) ──
    {
        id: "fresher-launch",
        name: "Launch",
        description: "Professional sidebar layout with layered depth and accent borders.",
        preview: "",
        tags: ["Professional", "Sidebar", "Clean"],
        recommendedFor: ["fresher"],
        defaultColors: { primary: "#0EA5E9", secondary: "#F0F9FF", accent: "#0284C7", background: "#FFFFFF", surface: "#F8FAFC", text: "#0F172A", textSecondary: "#64748B" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 80, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 135 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "fresher-aurora",
        name: "Aurora",
        description: "Immersive dark design with animated aurora background and glassmorphism.",
        preview: "",
        tags: ["Dark", "Creative", "Premium"],
        recommendedFor: ["fresher", "designer"],
        defaultColors: { primary: "#10B981", secondary: "#064E3B", accent: "#34D399", background: "#022C22", surface: "#064E3B", text: "#ECFDF5", textSecondary: "#A7F3D0" },
        defaultFonts: { heading: "'Outfit', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "parallax", scrollThreshold: 0.1, hoverEffects: ["lift", "glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 120, reducedMotion: false },
        visualStyle: { glassmorphism: true, glassBlur: 24, glassOpacity: 0.15, shadowLevel: "glow", auroraBackground: true, auroraColors: ["#10B981", "#3B82F6", "#8B5CF6"], meshGradient: false, meshColors: [], spotlightEffect: true, spotlightColor: "#34D39920", patternOverlay: "none", gradientAngle: 45 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "fresher-bolt",
        name: "Bolt",
        description: "High-energy dynamic layout with sharp typography and vibrant accents.",
        preview: "",
        tags: ["Vibrant", "Modern", "Dynamic"],
        recommendedFor: ["fresher"],
        defaultColors: { primary: "#F43F5E", secondary: "#FFF1F2", accent: "#E11D48", background: "#FFFFFF", surface: "#FFF1F2", text: "#4C0519", textSecondary: "#9F1239" },
        defaultFonts: { heading: "'Space Grotesk', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "slide-left", scrollThreshold: 0.1, hoverEffects: ["scale"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "lg", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 155 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "fresher-pure",
        name: "Pure",
        description: "Elegant minimalist layout with refined typography and soft depth effects.",
        preview: "",
        tags: ["Minimal", "Elegant", "Clean"],
        recommendedFor: ["fresher", "professional"],
        defaultColors: { primary: "#64748B", secondary: "#F8FAFC", accent: "#475569", background: "#FFFFFF", surface: "#F8FAFC", text: "#1E293B", textSecondary: "#64748B" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "600", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.2, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "sm", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    // ── Professional Templates (4) ──
    {
        id: "professional-elite",
        name: "Elite",
        description: "Sophisticated corporate design with a gold accent palette and premium feel.",
        preview: "",
        tags: ["Corporate", "Elite", "Luxury"],
        recommendedFor: ["professional", "executive"],
        defaultColors: { primary: "#1E293B", secondary: "#F8FAFC", accent: "#B45309", background: "#FFFFFF", surface: "#F1F5F9", text: "#0F172A", textSecondary: "#475569" },
        defaultFonts: { heading: "'Cormorant Garamond', serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-in", scrollThreshold: 0.15, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "professional-corporate",
        name: "Corporate",
        description: "Trustworthy and reliable layout with a structured grid and navy blue tones.",
        preview: "",
        tags: ["Corporate", "Trust", "Grid"],
        recommendedFor: ["professional"],
        defaultColors: { primary: "#1E3A8A", secondary: "#EFF6FF", accent: "#3B82F6", background: "#FFFFFF", surface: "#F8FAFC", text: "#1E293B", textSecondary: "#64748B" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 80, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "sm", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "professional-studio",
        name: "Studio",
        description: "Modern agency-style layout with large visuals and smooth page transitions.",
        preview: "",
        tags: ["Agency", "Modern", "Visual"],
        recommendedFor: ["professional", "freelancer"],
        defaultColors: { primary: "#000000", secondary: "#F3F4F6", accent: "#6366F1", background: "#FFFFFF", surface: "#F9FAFB", text: "#111827", textSecondary: "#6B7280" },
        defaultFonts: { heading: "'Syne', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "typewriter", scrollThreshold: 0.1, hoverEffects: ["scale", "glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 120, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "xl", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: true, spotlightColor: "#6366F108", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "professional-executive",
        name: "Executive",
        description: "Powerful and minimalist design with a focus on leadership and experience.",
        preview: "",
        tags: ["Leadership", "Minimal", "Executive"],
        recommendedFor: ["professional", "executive"],
        defaultColors: { primary: "#111827", secondary: "#F9FAFB", accent: "#000000", background: "#FFFFFF", surface: "#F3F4F6", text: "#111827", textSecondary: "#6B7280" },
        defaultFonts: { heading: "'Playfair Display', serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "sm", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    // ── Freelancer Templates (5) ──
    {
        id: "freelancer-brand",
        name: "Brand",
        description: "Bold personal branding design with large typography and vibrant colors.",
        preview: "",
        tags: ["Branding", "Bold", "Creative"],
        recommendedFor: ["freelancer"],
        defaultColors: { primary: "#EC4899", secondary: "#FDF2F8", accent: "#BE185D", background: "#FFFFFF", surface: "#FDF2F8", text: "#500724", textSecondary: "#9D174D" },
        defaultFonts: { heading: "'Archivo', sans-serif", headingWeight: "900", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "scale-up", scrollThreshold: 0.1, hoverEffects: ["scale"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "lg", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 135 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "freelancer-creative",
        name: "Creative",
        description: "Playful and colorful layout with bento grid elements and soft shadows.",
        preview: "",
        tags: ["Playful", "Creative", "Bento"],
        recommendedFor: ["freelancer", "designer"],
        defaultColors: { primary: "#F59E0B", secondary: "#FFFBEB", accent: "#D97706", background: "#FFFFFF", surface: "#FFFBEB", text: "#78350F", textSecondary: "#B45309" },
        defaultFonts: { heading: "'Outfit', sans-serif", headingWeight: "700", body: "'DM Sans', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 80, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "circles", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "freelancer-vivid",
        name: "Vivid",
        description: "High-contrast design with large headers and a unique asymmetric structure.",
        preview: "",
        tags: ["Vivid", "Bold", "Asymmetric"],
        recommendedFor: ["freelancer"],
        defaultColors: { primary: "#8B5CF6", secondary: "#1E1B4B", accent: "#C084FC", background: "#0F172A", surface: "#1E293B", text: "#F8FAFC", textSecondary: "#CBD5E1" },
        defaultFonts: { heading: "'Space Grotesk', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "slide-right", scrollThreshold: 0.1, hoverEffects: ["scale", "glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 120, reducedMotion: false },
        visualStyle: { glassmorphism: true, glassBlur: 12, glassOpacity: 0.1, shadowLevel: "xl", auroraBackground: false, auroraColors: [], meshGradient: true, meshColors: ["#8B5CF6", "#EC4899", "#3B82F6"], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 135 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "freelancer-sleek",
        name: "Sleek",
        description: "Sophisticated minimalist layout with a focus on typography and subtle motion.",
        preview: "",
        tags: ["Sleek", "Minimalist", "Modern"],
        recommendedFor: ["freelancer", "professional"],
        defaultColors: { primary: "#111827", secondary: "#F9FAFB", accent: "#6366F1", background: "#FFFFFF", surface: "#F9FAFB", text: "#111827", textSecondary: "#4B5563" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-in", scrollThreshold: 0.15, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "sm", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "freelancer-folio",
        name: "Folio+",
        description: "Large-scale project gallery with immersive transitions and bold technology tags.",
        preview: "",
        tags: ["Gallery", "Immersive", "Bold"],
        recommendedFor: ["freelancer", "designer"],
        defaultColors: { primary: "#000000", secondary: "#F4F4F5", accent: "#000000", background: "#FFFFFF", surface: "#F4F4F5", text: "#000000", textSecondary: "#52525B" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "900", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "scale-up", scrollThreshold: 0.1, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 150, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "xl", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    // ── Developer Templates (5) ──
    {
        id: "developer-matrix",
        name: "Terminal",
        description: "Retro terminal-inspired design with fixed-width typography and scanlines.",
        preview: "",
        tags: ["Terminal", "Retro", "Tech"],
        recommendedFor: ["developer"],
        defaultColors: { primary: "#10B981", secondary: "#064E3B", accent: "#10B981", background: "#000000", surface: "#050505", text: "#10B981", textSecondary: "#059669" },
        defaultFonts: { heading: "'IBM Plex Sans', sans-serif", headingWeight: "700", body: "'Share Tech Mono', monospace", bodyWeight: "400", mono: "'Share Tech Mono', monospace" },
        animationProfile: { scrollType: "typewriter", scrollThreshold: 0.05, hoverEffects: ["glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 50, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "none", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "grid", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "developer-codebase",
        name: "Codebase",
        description: "GitHub/VS Code-inspired layout with dark mode and syntax highlighting colors.",
        preview: "",
        tags: ["GitHub", "Code", "Dark"],
        recommendedFor: ["developer"],
        defaultColors: { primary: "#3B82F6", secondary: "#1E293B", accent: "#60A5FA", background: "#0D1117", surface: "#161B22", text: "#C9D1D9", textSecondary: "#8B949E" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.1, hoverEffects: ["lift", "border-glow"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 80, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "md", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "developer-linear",
        name: "Linear",
        description: "Modern SaaS-style layout with sleek dark gradients and subtle glass effects.",
        preview: "",
        tags: ["SaaS", "Modern", "Sleek"],
        recommendedFor: ["developer", "freelancer"],
        defaultColors: { primary: "#FFFFFF", secondary: "#111111", accent: "#6366F1", background: "#000000", surface: "#0A0A0A", text: "#FFFFFF", textSecondary: "#888888" },
        defaultFonts: { heading: "'Inter', sans-serif", headingWeight: "800", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'JetBrains Mono', monospace" },
        animationProfile: { scrollType: "blur-in", scrollThreshold: 0.1, hoverEffects: ["glow", "lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 100, reducedMotion: false },
        visualStyle: { glassmorphism: true, glassBlur: 16, glassOpacity: 0.05, shadowLevel: "xl", auroraBackground: false, auroraColors: [], meshGradient: true, meshColors: ["#000000", "#111111", "#1A1A1A"], spotlightEffect: true, spotlightColor: "#6366F105", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "developer-mono",
        name: "Mono",
        description: "Minimalist monospace design with a focus on technical clarity and structure.",
        preview: "",
        tags: ["Mono", "Minimal", "Technical"],
        recommendedFor: ["developer"],
        defaultColors: { primary: "#000000", secondary: "#F3F4F6", accent: "#000000", background: "#FFFFFF", surface: "#F9FAFB", text: "#000000", textSecondary: "#6B7280" },
        defaultFonts: { heading: "'JetBrains Mono', monospace", headingWeight: "800", body: "'JetBrains Mono', monospace", bodyWeight: "400", mono: "'JetBrains Mono', monospace" },
        animationProfile: { scrollType: "fade-up", scrollThreshold: 0.2, hoverEffects: ["lift"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 50, reducedMotion: false },
        visualStyle: { glassmorphism: false, glassBlur: 0, glassOpacity: 1, shadowLevel: "none", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: false, spotlightColor: "", patternOverlay: "none", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
    {
        id: "developer-quantum",
        name: "Quantum",
        description: "Futuristic layout with complex grid patterns and neon-cyan highlights.",
        preview: "",
        tags: ["Futuristic", "Neon", "Grid"],
        recommendedFor: ["developer"],
        defaultColors: { primary: "#22D3EE", secondary: "#083344", accent: "#06B6D4", background: "#020617", surface: "#0F172A", text: "#F1F5F9", textSecondary: "#94A3B8" },
        defaultFonts: { heading: "'Orbitron', sans-serif", headingWeight: "700", body: "'Inter', sans-serif", bodyWeight: "400", mono: "'Fira Code', monospace" },
        animationProfile: { scrollType: "flip", scrollThreshold: 0.1, hoverEffects: ["glow", "tilt"], staggerReveal: true, staggerDelay: 0, staggerIncrement: 120, reducedMotion: false },
        visualStyle: { glassmorphism: true, glassBlur: 10, glassOpacity: 0.1, shadowLevel: "glow", auroraBackground: false, auroraColors: [], meshGradient: false, meshColors: [], spotlightEffect: true, spotlightColor: "#22D3EE10", patternOverlay: "grid", gradientAngle: 180 },
        supportsImage: true,
        sections: defaultSections.map(function (s) { return (__assign({}, s)); }),
    },
];
// ─── Helper Functions ─────────────────────────────────────────────
var getGoogleFontsUrl = function (fonts) {
    var families = [fonts.heading, fonts.body, fonts.mono]
        .map(function (f) { return f.replace(/'/g, "").replace(/\s+/g, "+"); })
        .filter(function (v, i, a) { return a.indexOf(v) === i; });
    return "https://fonts.googleapis.com/css2?family=".concat(families.join("&family="), "&display=swap");
};
exports.getGoogleFontsUrl = getGoogleFontsUrl;
exports.ThemeRegistry = {
    getAll: function () { return exports.THEME_PRESETS; },
    getById: function (id) { return exports.THEME_PRESETS.find(function (t) { return t.id === id; }) || exports.THEME_PRESETS[0]; },
    getByCategory: function (cat) {
        return cat === "all" ? exports.THEME_PRESETS : exports.THEME_PRESETS.filter(function (t) { return t.recommendedFor.includes(cat); });
    },
};
exports.PREMIUM_LAYOUTS = [
    { id: "cinematic-parallax", name: "Cinematic Parallax", description: "Agency-level 3D scrolling and masking" },
    { id: "bento-grid-interactive", name: "Interactive Bento", description: "Vercel-inspired dense grid dashboard" },
    { id: "immersive-glass", name: "Immersive Glass", description: "Apple-style spatial depth and blur" },
    { id: "editorial-asymmetry", name: "Editorial Asymmetry", description: "High-fashion Vogue magazine spread" },
    { id: "brutalist-neo", name: "Neo Brutalism", description: "Trendy studio loud and bold aesthetics" },
];
exports.CURATED_TEMPLATES = [
    { id: "tpl-cinematic", name: "The Agency", layout: "cinematic-parallax", theme: "executive-obsidian", preview: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&q=80", description: "Deep dark cinematic masking." },
    { id: "tpl-bento", name: "Software Pro", layout: "bento-grid-interactive", theme: "midnight-cobalt", preview: "https://images.unsplash.com/photo-1618477247222-acaff912bb64?w=400&q=80", description: "Tech dashboard aesthetic." },
    { id: "tpl-glass", name: "Vision Spatial", layout: "immersive-glass", theme: "ivory-minimalist", preview: "https://images.unsplash.com/photo-1558655146-d09347e92766?w=400&q=80", description: "Spatial computing glass floating UI." },
    { id: "tpl-editorial", name: "High Fashion", layout: "editorial-asymmetry", theme: "slate-rust", preview: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80", description: "Vogue-style broken grid." },
    { id: "tpl-brutalist", name: "Trendy Studio", layout: "brutalist-neo", theme: "neon-cyber", preview: "https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=400&q=80", description: "Loud, bold, marquee brutalism." },
];
var getDefaultCustomization = function (layoutId, themeId) {
    var t = exports.ThemeRegistry.getById(themeId);
    return {
        themeId: themeId,
        colors: __assign({}, t.defaultColors),
        fonts: __assign({}, t.defaultFonts),
        animation: __assign({}, t.animationProfile),
        visualStyle: __assign({}, t.visualStyle),
        layout: layoutId,
        imageShape: "circle",
        imageSize: "medium",
        showSectionNumbers: false,
        sectionInstances: t.sections.map(function (s) { return (__assign({}, s)); }),
        sectionVariants: {},
        elementStyles: {},
    };
};
exports.getDefaultCustomization = getDefaultCustomization;
