import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import type { PortfolioData, CustomizationOptions } from "@/lib/portfolio-templates";
import useEditorStore from "@/store/editor-store";
import { getDefaultCustomization, ThemeRegistry, DEFAULT_SECTIONS } from "@/lib/portfolio-templates";
import { generatePortfolioHTML } from "@/lib/template-renderer";

type RouteState = {
  parsedData?: any;
  enhancedData?: any;
  fileName?: string;
  selectedTemplateId?: string;
} | null;

function coercePortfolioData(parsedData: any, enhancedData: any): PortfolioData {
  const fallback: PortfolioData = {
    name: "Your Name",
    title: "Software Engineer",
    email: "",
    phone: "",
    location: "",
    linkedin: "",
    github: "",
    website: "",
    summary: "",
    bio: "",
    skills: [],
    experience: [],
    education: [],
    projects: [],
    certifications: [],
    languages: [],
    interests: [],
    profileImage: null,
  };

  if (!parsedData) return fallback;

  return {
    name: parsedData.name || fallback.name,
    title: parsedData.title || fallback.title,
    email: parsedData.email || fallback.email,
    phone: parsedData.phone || fallback.phone,
    location: parsedData.location || fallback.location,
    linkedin: parsedData.linkedin || fallback.linkedin,
    github: parsedData.github || fallback.github,
    website: parsedData.website || fallback.website,
    summary: enhancedData?.enhanced_summary ?? parsedData.summary ?? parsedData.bio ?? fallback.summary,
    bio: enhancedData?.enhanced_bio ?? parsedData.bio ?? parsedData.summary ?? fallback.bio,
    skills: parsedData.skills || fallback.skills,
    experience: (parsedData.experience || []).map((exp: any) => ({
      company: exp.company || "",
      role: exp.role || "",
      duration: exp.duration || "",
      description: exp.description || "",
      highlights: exp.highlights || [],
    })),
    education: (parsedData.education || []).map((edu: any) => ({
      institution: edu.institution || "",
      degree: edu.degree || "",
      duration: edu.duration || "",
      gpa: edu.gpa || "",
      highlights: edu.highlights || [],
    })),
    projects: (parsedData.projects || []).map((proj: any) => ({
      name: proj.name || "",
      description: proj.description || "",
      technologies: proj.technologies || [],
      link: proj.link || "",
    })),
    certifications: parsedData.certifications || fallback.certifications,
    languages: parsedData.languages || fallback.languages,
    interests: parsedData.interests || fallback.interests,
    profileImage: null,
  };
}

function setByField(data: PortfolioData, field: string, value: string): PortfolioData {
  // Supported editable fields (generated by frontend/src/lib/template-renderer.ts)
  if (field === "name") return { ...data, name: value };
  if (field === "title") return { ...data, title: value };
  if (field === "summary") return { ...data, summary: value };

  if (field === "skills") {
    const nextSkills = value
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);
    return { ...data, skills: nextSkills };
  }

  // experience.<idx>.<key>
  const expMatch = field.match(/^experience\.(\d+)\.(.+)$/);
  if (expMatch) {
    const idx = Number(expMatch[1]);
    const key = expMatch[2] as keyof PortfolioData["experience"][number];
    if (!Number.isFinite(idx)) return data;

    const next = [...data.experience];
    if (!next[idx]) return data;
    const nextItem: any = { ...next[idx] };

    if (key === "description") nextItem.description = value;
    else if (key === "role") nextItem.role = value;
    else if (key === "company") nextItem.company = value;
    else if (key === "duration") nextItem.duration = value;

    next[idx] = nextItem;
    return { ...data, experience: next };
  }

  // projects.<idx>.<key>
  const projMatch = field.match(/^projects\.(\d+)\.(.+)$/);
  if (projMatch) {
    const idx = Number(projMatch[1]);
    const key = projMatch[2] as keyof PortfolioData["projects"][number];
    if (!Number.isFinite(idx)) return data;

    const next = [...data.projects];
    if (!next[idx]) return data;
    const nextItem: any = { ...next[idx] };

    if (key === "name") nextItem.name = value;
    else if (key === "description") nextItem.description = value;
    else if (key === "link") nextItem.link = value;
    else if (key === "technologies") {
      nextItem.technologies = value
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
    }

    next[idx] = nextItem;
    return { ...data, projects: next };
  }

  // education.<idx>.<key>
  const eduMatch = field.match(/^education\.(\d+)\.(.+)$/);
  if (eduMatch) {
    const idx = Number(eduMatch[1]);
    const key = eduMatch[2] as keyof PortfolioData["education"][number];
    if (!Number.isFinite(idx)) return data;

    const next = [...data.education];
    if (!next[idx]) return data;
    const nextItem: any = { ...next[idx] };

    if (key === "institution") nextItem.institution = value;
    else if (key === "degree") nextItem.degree = value;
    else if (key === "duration") nextItem.duration = value;
    else if (key === "gpa") nextItem.gpa = value;
    else {
      // ignore unknown keys
      return data;
    }

    next[idx] = nextItem;
    return { ...data, education: next };
  }

  return data;
}

export function TemplateEditorCanvas() {
  const location = useLocation();
  const routeState = (location.state ?? null) as RouteState;

  const { customization, setTheme, setPortfolioData, portfolioData } = useEditorStore();

  const initialData = useMemo(
    () => coercePortfolioData(routeState?.parsedData, routeState?.enhancedData),
    [routeState?.parsedData, routeState?.enhancedData]
  );

  const [localData, setLocalData] = useState<PortfolioData>(initialData);

  useEffect(() => {
    setLocalData(initialData);
    setPortfolioData(initialData);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialData]);

  const resolvedTemplateId = routeState?.selectedTemplateId ?? customization.themeId;

  useEffect(() => {
    if (!resolvedTemplateId) return;
    if (customization.themeId !== resolvedTemplateId) setTheme(resolvedTemplateId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [resolvedTemplateId]);

  const resolvedCustomization: CustomizationOptions = useMemo(() => {
    const fallback = getDefaultCustomization();
    const theme = ThemeRegistry.getById(resolvedTemplateId);

    return {
      ...fallback,
      ...customization,
      themeId: resolvedTemplateId,
      colors: (customization as any).colors ?? theme.defaultColors,
      sectionInstances:
        (customization as any).sectionInstances?.length > 0
          ? (customization as any).sectionInstances
          : fallback.sectionInstances ?? DEFAULT_SECTIONS,
    };
  }, [customization, resolvedTemplateId]);

  const containerRef = useRef<HTMLDivElement | null>(null);

  const effectiveData = portfolioData ?? localData;

  const html = useMemo(() => {
    return generatePortfolioHTML(effectiveData, resolvedCustomization, true);
  }, [effectiveData, resolvedCustomization]);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;

    const onBlurCapture = (e: FocusEvent) => {
      const target = e.target as HTMLElement | null;
      if (!target) return;

      const field = target.getAttribute("data-field");
      if (!field) return;

      const nextValue = (target.textContent ?? "").trim();

      const nextData = setByField(effectiveData, field, nextValue);
      setLocalData(nextData);
      setPortfolioData(nextData);
    };

    el.addEventListener("blur", onBlurCapture, true);
    return () => el.removeEventListener("blur", onBlurCapture, true);
  }, [effectiveData, setPortfolioData]);

  return (
    <div className="w-full">
      <div
        ref={containerRef}
        className="w-full"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
